name: Generate README

on:
  push:
    paths:
      - 'data_sources.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: bundle install

    - name: Generate README
      run: bundle exec ruby src/generate_readme.rb

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit changes
      if: steps.git-check.outputs.changes == 'true'
      uses: EndBug/add-and-commit@v9
      with:
        add: 'README.md'
        message: "🤖 Update `README.md` from `data_sources.json`."
        default_author: github_actions
